### ISSUE TITLE
Fix

### ISSUE THREAD

**Issue by dragoncity17** [chriskomus/aliexpress-order-downloader#1]

**Comment by dragoncity17** [comment]
Edit : Now doesn't work... don't see buttons... do you know what ?

**Comment by chriskomus** [comment]
Hi, thanks for testing it out.

I suspect the date issue has to do with how AliExpress displays dates in different locations. I tested using 'en-US' and  'nl-NL' and had no issues. How does Ali display date for you? For me its 'Mar 28, 2022'. The function getDate() is taking the string in that format and attempting to convert it into a Date object.

**Comment by chriskomus** [comment]
Currently tracking # info is only available on the order detail script, not the order list script, so I have removed the empty columns. I'm having issues with merging the jsonp tracking info into the order array before exporting to the clipboard. So that is currently a work in progress! There is probably a workaround using promises.

Since Ali doesn't display product data on the order list for orders that contain more than 1 item, those fields will also be blank.

I'm hoping to find a workaround for these issues, but currently opening each order in a new tab and then copying each order will give the most amount of detail, including all product detail and tracking numbers.
